### ISSUE TITLE
2024.5.7meeting

### ISSUE THREAD

**Issue by Maggiexz** [qingdaoalex/CITS5505-Project2#16]
What we done:

- Yunfang Lyu: complete authentication in every input and fix the upload avatar feature bug.
- Xiao Zhang: complete the "send private message" feature and display the notification in the navbar.
- Zhuowen Wu: complete the "reply posts" feature in flask.
- Alex Wang: build the basic front-end framework of the index page.

Next step task assignments:

- Yunfang Lyu: fix the avatar size bug and add LIVE2D model.
- Xiao Zhang: add welcome page.
- Zhuowen Wu: Add display of data related to posts and add search feature.
- Alex Wang: Beautify web pages with a unified style.

**Comment by qingdaoalex** [comment]
All the tasks already finished and tested.
